### ISSUE TITLE
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'new'

### ISSUE THREAD

**Issue by monajalal** [gkchai/GestureRecognition#1]
```
mona@Mona:~/code/gesture/GestureRecognition$ python train.py --new --model MLP --num_of_steps=20000
/home/mona/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "train.py", line 24, in <module>
    tf.flags.DEFINE_string("train_dir", os.path.join("train_dir", FLAGS.model), "Directory for saving and loading checkpoints.")
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 630, in __call__
    name, value, suggestions=suggestions)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'new'


```
how should I fix this?

**Comment by gkchai** [comment]
The way flags are handled changed in recent TF version. Fixed in https://github.com/gkchai/GestureRecognition/commit/0ad2cab1074504fa65e9db20573ff75acb80756f
