### ISSUE TITLE
TypeError: Fetch argument dict_values([<tf.Tensor 'accuracy/update_op:0' shape=() dtype=float32>, <tf.Tensor 'precision/update_op:0' shape=() dtype=float32>, <tf.Tensor 'recall/update_op:0' shape=() dtype=float32>]) has invalid type <class 'dict_values'>, must be a string or Tensor. (Can not convert a dict_values into a Tensor or Operation.)

### ISSUE THREAD

**Issue by monajalal** [gkchai/GestureRecognition#3]
How should I fix this?

```
mona@Mona:~/code/gesture/GestureRecognition$ python evaluate.py  --model MLP
/home/mona/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-06-22 09:44:50.364072: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-22 09:44:50.499371: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 11.90GiB freeMemory: 11.11GiB
2018-06-22 09:44:50.499398: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-06-22 09:44:50.691053: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-06-22 09:44:50.691082: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-06-22 09:44:50.691087: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
Traceback (most recent call last):
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 282, in __init__
    fetch, allow_tensor=True, allow_operation=True))
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3587, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3679, in _as_graph_element_locked
    types_str))
TypeError: Can not convert a dict_values into a Tensor or Operation.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "evaluate.py", line 88, in <module>
    tf.app.run(main)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "evaluate.py", line 84, in main
    session_config=config.session_config,
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/evaluation.py", line 301, in evaluation_loop
    timeout=timeout)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/training/python/training/evaluation.py", line 450, in evaluate_repeatedly
    session.run(eval_ops, feed_dict)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 567, in run
    run_metadata=run_metadata)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1043, in run
    run_metadata=run_metadata)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1134, in run
    raise six.reraise(*original_exc_info)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1119, in run
    return self._sess.run(*args, **kwargs)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1191, in run
    run_metadata=run_metadata)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 971, in run
    return self._sess.run(*args, **kwargs)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 427, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 247, in for_fetch
    return _DictFetchMapper(fetch)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 385, in __init__
    _FetchMapper.for_fetch(fetch) for fetch in fetches.values()
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 385, in <listcomp>
    _FetchMapper.for_fetch(fetch) for fetch in fetches.values()
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 245, in for_fetch
    return _ListFetchMapper(fetch)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 352, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 352, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 253, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 286, in __init__
    (fetch, type(fetch), str(e)))
TypeError: Fetch argument dict_values([<tf.Tensor 'accuracy/update_op:0' shape=() dtype=float32>, <tf.Tensor 'precision/update_op:0' shape=() dtype=float32>, <tf.Tensor 'recall/update_op:0' shape=() dtype=float32>]) has invalid type <class 'dict_values'>, must be a string or Tensor. (Can not convert a dict_values into a Tensor or Operation.)

```

**Comment by gkchai** [comment]
Error was due to the dict data structure changes in Python 3.x. Fixed in https://github.com/gkchai/GestureRecognition/commit/7c3f14b52280383989995317867321b6b532f406
